### ISSUE TITLE
Syntax error in Webhook update Docs 

### ISSUE THREAD

**Issue by iamcaleberic** [smooch/smooch-ruby#14]
- There is a syntax error in the webhook update docs, missing a `,`

```
....
begin
  result = api_instance.update_webhook(app_id, webhook_idwebhook_update_body)
  p result
.....
````

https://github.com/smooch/smooch-ruby/blob/master/docs/WebhookApi.md#update_webhook

**Comment by dhayhak** [comment]
👋  @iamcaleberic, 

The wrong generated ruby code in the docs has been fixed in `v5.16.1`.
