### ISSUE TITLE
Errors when linking AppUsers

### ISSUE THREAD

**Issue by ferreiraandy** [smooch/smooch-ruby#18]
Everytime then I try to link an User to a channel i've been receiving this erro:

```ruby
{"error":{"code":"integration_not_found","description":"Integration not found"}}
```

However, I've only receive this information by debuging the gem.
Do I need create an integration to Whats App in order to use this channel? Or It is skiping sothing on gem?

**Comment by mspensieri** [comment]
> Do I need create an integration to Whats App in order to use this channel?

Yes, you must have an active WhatsApp integration in order to link WhatsApp to a user.
