### ISSUE TITLE
API is not authorizing

### ISSUE THREAD

**Issue by angelacode** [smooch/smooch-ruby#3]
After generating my `jwt` and going through the steps, I still get a non authorized error or a not found error:

https://github.com/smooch/smooch-ruby/blob/master/docs/ConversationApi.md#post_message

```
2017-05-24 22:18:18 - SmoochApi::ApiError - Not Found:
```

**Comment by mspensieri** [comment]
I'm not sure if this is an issue with the ruby wrapper itself or just a jwt generation / authentication issue. If you send an email to help@smooch.io with the details of your request and the JWT you are using someone can help you out there :)
