### ISSUE TITLE
How do I access the ref value in messenger?

### ISSUE THREAD

**Issue by angelacode** [smooch/smooch-ruby#6]
In messenger, I can do m.me/bot?ref=hello

I would like to access that ref value.  How do I do that?

**Comment by angelacode** [comment]
Hi, following up to see how to access the ref info that messenger makes available, thanks!

**Comment by mspensieri** [comment]
I don't think we currently expose that information. I'll file an improvement request in our backlog

**Comment by angelacode** [comment]
Hi, I saw a product update which says that the ref is associated with a conversation:start.

However, after creating a webhook for it, I still don't see the event hit my webhook.

**Comment by angelacode** [comment]
https://docs.smooch.io/rest/#conversation-events

**Comment by angelacode** [comment]
<img width="1014" alt="screen shot 2017-07-03 at 7 52 04 pm" src="https://user-images.githubusercontent.com/190438/27813203-22a611e0-6029-11e7-9979-b6102425c8f0.png">

**Comment by mspensieri** [comment]
That webhook event currently only works for referrals from Facebook ads, support for `m.me` links with a referral param is coming up soon. I'll update this issue when it's live

**Comment by angelacode** [comment]
Oh I thought they were the same, thanks!

**Comment by angelacode** [comment]
Would conversation:start Post to the web hook?  Didn't seem like anything but maybe a HEAD request came through.

**Comment by jugarrit** [comment]
We've updated that webhook to now trigger on `m.me` links.
Give it a shot!

**Comment by angelacode** [comment]
wow this  was faster than I expected...I built my own but would prefer to use the smooch API....I tested it and I do receive the triggered request!  Thanks!
