### ISSUE TITLE
sending events when hitting the m.me/ link

### ISSUE THREAD

**Issue by angelacode** [smooch/smooch-ruby#8]
I set up my webhook when there are conversations, so I would expect to see a POST when hitting the m.me/ link....but I don't.

![image](https://user-images.githubusercontent.com/190438/28647988-6692dbce-721f-11e7-9a0e-ed2fafbcfd6a.png)

**Comment by angelacode** [comment]
I set the Triggers for the webhook to include convesration:start -- that's the one that's triggered when someone first hits the m.me/ link right?

**Comment by angelacode** [comment]
Hi, MIke -- do you have a timeline, I'm realizing I need to know the referral to build up the app to get better traction so need to know whether we need to build this ourselves or just wait for the feature on smooch....?

**Comment by mspensieri** [comment]
The `conversation:start` event is triggered when the user taps the "Get Started" button for your page, or when they accept a message request sent via the [linking API](https://docs.smooch.io/rest/#link-app-user-to-channel). In the case where the user clicks an `m.me` link, `conversation:start` would only fire if the Get Started button is presented and the user taps it.

When you configure your page with Smooch, it should automatically add a Get Started button for you - does your page have one?

**Comment by angelacode** [comment]
Oh, I see.  Currently there is no Get Started button...there isn't one added, nor is it in the Messenger client.

What I want to do is to know which trigger keyword to use based on which m.me link is clicked.  I have different bots with different keywords which I would use as the ref parameter.

This way I can solve for the following use-case: 1) When a user clicks on the m.me/link, the bot auto-starts based on the known ref value; 2) I can deliver link-specific content.

This make sense?

**Comment by angelacode** [comment]
Hi, I have done a workaround, but it is limited without being part of the Smooch API.  I have my Facebook Messenger server listen for the event referral (and I turned off all other events).

I then take the referral param and process a response.  Because it doesn't go thorugh the smooch API, however, I don't know the smooch userID and so cannot really communicate consistently since the rest of the communications go through smooch.

So I solve one problem which is being able to instrument and have the bot respond when clicking through a m.me link, but it's sort of fragmented now.

Timing on when referral params will be availble via smooch?

**Comment by mspensieri** [comment]
I don't have an exact timeline but I would suspect somewhere within the next 2-3 weeks

**Comment by mspensieri** [comment]
This was fixed at the same time as #6. If your page has a get started button, and you link the user via an m.me link, then a `conversation:start` webhook will be triggered with the referral param when the user clicks the button
