### ISSUE TITLE
whitelist smooch IP addresses?

### ISSUE THREAD

**Issue by angelacode** [smooch/smooch-ruby#9]
Hi, my webhook is out in the wild, is there a way for me to set up the firewall to only allow requests from smoch?

**Comment by mspensieri** [comment]
Smooch doesn't currently use static IPs, so we aren't able to provide a whitelist that you can configure on your side. This is something we're working on, though.

See [Securing a webhook](https://docs.smooch.io/rest/#securing-a-webhook) for details on how to validate that Smooch is the source of the webhook event
